### ISSUE TITLE
XCFramework for Carthage

### ISSUE THREAD

**Issue by reypena-bandlab** [Purchasely/Purchasely-iOS#27]
We are unable are unable to get the `.xcframework` via carthage. Is it possible to support it since our project is setup to only support this framework type for all 3rd party libraries. I believe only SPM supports xcframework for now.

**Comment by EPIKorial** [comment]
Hello @reypena-bandlab, thanks for reaching out to us about this matter. You are right, at the moment when using **Carthage**, you only get the ` .framework` version of our SDK. 

We are working on it as i speak to improve that and provide a way of getting the `xcframework` through **Carthage**. However in the meantime you should be able to use our SDK by using the following steps:

- Adding `binary "https://raw.githubusercontent.com/Purchasely/Purchasely-iOS/master/Purchasely.json"` to your _Cartfile_
- Using `carthage update --use-xcframeworks` command
- Importing the **Purchasely.framework** in your _**Frameworks, Libraries and Embedded**_ content section in your _**Target**_ **_General tab_**.
- Running your application on a ### device **(not a simulator, since it looks like Carthage only get the iOS build)**

This is only a workaround but it should allows you to integrate and use our SDK until we release the `.xcframework` for **Carthage**.

Thank you for your understanding,

Best regards

**Comment by reypena-bandlab** [comment]
Hi @EPIKorial ,

Thank you for getting back to us. We have already tried that and integrated the SDK. However, our CI fails since we use `tuist` to generate the configure the project but our setup expects `xcframeworks`. We can still continue development locally but unfortunately unable to create release version using our CI/CD. 

I see Pods and SPM already is setup. Is there any ETA your team have in mind to be able to support this as it currently blocks our development. 🙏 

Best regards

**Comment by EPIKorial** [comment]
Hellp @reypena-bandlab, 

I've uploaded a solution that should work for you and allow you to continue your development using our SDK with Carthage.

Simply update the import line in your Cartfile from:

`binary "https://raw.githubusercontent.com/Purchasely/Purchasely-iOS/master/Purchasely.json"`

To this:
`binary "https://raw.githubusercontent.com/Purchasely/Purchasely-iOS/master/Purchasely-xcframework.json"
`
Let me know if this solves your issue,

Best regards,

Florian
